### PR TITLE
Fixes author info boxes with short bios

### PR DESCRIPTION
**Pull request by galengidman**
Currently, Gravatars aren't cleared in author info boxes. This causes incorrect vertical spacing when an author has a short bio length. Example: http://galen.in/IqS1wF

I believe I compiled the asset updates with a sightly newer version of Autoprefixer with removed a few vendor prefixes that had been there. Basically what would've happened if the project maintainer had run `npm update` and then `grunt`. Anyway, that's the reason for the additional file diffs.

### CODE REVIEW

**Comment by davidsherlock** [comment]
@galengidman, to fix the issue with the vendor prefixes use the following browser string: `last 5 version`.

If you re-compile you should have the correct (and original) prefixes. Additionally, good catch on the author box!

**Comment by galengidman** [comment]
@davidsherlock - There's no config for that in the Gruntfile (https://github.com/nDmitry/grunt-autoprefixer#options). Where should I be putting that?

**Comment by galengidman** [comment]
@davidsherlock - Obviously I could add it to the Gruntfile, but that seems a bit presumptuous.

**Comment by amdrew** [comment]
Thanks @galengidman, please see https://github.com/easydigitaldownloads/themedd/issues/115

Currently using the latest version of autoprefixer: https://github.com/easydigitaldownloads/themedd/blob/master/package.json#L13

Can't recall what it defaults to if you don't specify it in the config however I played around and liked the defaults. It definitely should not remove any of the current vendor prefixes when you run grunt, so not sure how that happened to you (ran npm update to be sure).

**Comment by galengidman** [comment]
@amdrew - Will do on the new PR. The Autoprefixer stuff is weird... I'll dig around a bit and see what I can find.

**Comment by amdrew** [comment]
Excellent, thanks @galengidman

**Pull request closed without merging**
