### PR TITLE
Commenting formatting fix

### PR DESCRIPTION
**Pull request by davidsherlock**
Fixed extra tab indent on comment.

### CODE REVIEW

**Comment by amdrew** [comment]
@davidsherlock Confused on why it was deleted and then re-added, was that a mistake? 

Want to fix up the comment so it lines up correctly? Looks like you've pulled it back a bit but it actually needs to be indented more. See the slim template for an example: https://github.com/easydigitaldownloads/themedd/blob/master/page-templates/slim.php#L23

**Comment by davidsherlock** [comment]
@amdrew, I used the web interface for quickness to upload the file but for some reason it deleted it as well (meh...). For some reason the alignment dosen't look right in the online code editor but should be perfect when downloaded.

**Comment by davidsherlock** [comment]
I use Atom, not sure about yourself? either way I did fix the issue with the comment but the online editor displays it differently.

**Comment by amdrew** [comment]
No worries. I merged but it needed to be indented a bit more, fixed! I use Atom also

**Pull request merged**
